### PR TITLE
Fix build and update node versions to test with

### PR DESCRIPTION
**Pull request by dominykas**
I will be looking into fixing #332 next, but I'd like to see a green build as a starting point.

I wasn't sure about the distinction between `master` and `dev`, so I started on `master`. I found the last green build and it was using an pinned `eslint` version - it seems the same version is also pinned on `dev` - I believe #323 has an attempt to upgrade `eslint` to something more modern, but my top priority here is getting rid of the XSS, so maybe some other day :)

I also restored some other deps, that were present in the last green build I could find (https://github.com/jonschlinkert/remarkable/tree/429881961da02f351393050a698c447376df5328).

### CODE REVIEW

**Comment by claudiopro** [comment]
Legend @dominykas 👍

**Comment by torkelo** [comment]
Can this be merged and the security fix as well? all repos using remarkable now have a big security GitHub warning.

**Comment by TrySound** [comment]
Build is fixed. Node versions upgraded. Thanks for heads up.

**Comment by dominykas** [comment]
Do you want me to rebase my other PRs?

**Comment by TrySound** [comment]
Sure would be great!

**Comment by dominykas** [comment]
Done. Thanks for bringing this back to life!

**Pull request closed without merging**
