### PR TITLE
Add plugin, parsing and rendering documentation

### PR DESCRIPTION
**Pull request by lemoinem**
I tried to check how to create new plugins for remarkable and noticed the documentation wasn't available yet. I checked the documentation provided by #211 or #48 but I didn't see anything that could be added to this PR.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
sorry this took so long!

**Comment by jonschlinkert** [comment]
and thank you, the docs are great!

**Comment by jonschlinkert** [comment]
@lemoinem I'd be happy to add you as a collab if you want

**Comment by lemoinem** [comment]
@jonschlinkert Thank you very much for the offer. However, I'm not sure I will have the time required to help support the project in any meaningful way...

Great work on the parser thought! Keep up the great work. I know time is pretty much THE resources everyone is missing these days...

**Pull request merged**
