### PR TITLE
Decouple linkify in separate plugin

### PR DESCRIPTION
**Pull request by TrySound**
Closes https://github.com/jonschlinkert/remarkable/issues/343

linkify depends on autolinker which is quite heavy. The option is
disabled by default and not used most of the time.

https://bundlephobia.com/result?p=autolinker@3.1.0

In this diff I decoupled linkify into plugin which can be accessed like
this

```js
import Remarkable from 'remarkable';
import linkify from 'remarkable/linkify';

const md = new Remarkable({ html: true })
  .use(linkify);
```

For UMD build linkify provided out of the box

```js
const md = new window.Remarkable({ html: true })
  .use(window.Remarkable.linkify);
```

### CODE REVIEW

**Comment by TrySound** [comment]
@jonschlinkert @doowb  @shockey are you okay with this change?

**Comment by doowb** [comment]
I like the change, it looks great!

I'm assuming the reason for doing it this way is because it gives bundlers a chance to tree shake and exclude `autolinker` from the bundle when `linkify` is not used.

I think this change should wait until a major version bump is ready. Even though the default for `linkify` is `false`, any users that have `linkify` set to `true` will have different behavior and will need to upgrade.

**Comment by TrySound** [comment]
I can add warning that linkify option is replaced with plugin. Major bump is almost ready (at least from my POV). This PR is a blocker for https://github.com/jonschlinkert/remarkable/pull/350.

**Comment by doowb** [comment]
In #350 you mentioned: `internals are hidden and changing them will not affect users`. I assumed that once the changes are made and the code is bundled that version `1.7.2` could be published . Then `2.0.0` could be published with this PR (and any others that might have a breaking change).

If you're saying that all of the other stuff would require a major bump, then I'm fine with this PR being merged now. Especially because I'm excited to see all the work you've been doing get released 😀 , but I'm still wary about breaking changes in a patch bump.

If you have a plan for the releases, I'm good with that and I'll approve my review.

**Comment by TrySound** [comment]
I think removed bower support is a breaking change so we cannot publish 1.7.2.

**Pull request merged**
