### PR TITLE
Typings for TypeScript

### LINKED ISSUE #221: Typings for TypeScript
Would be great to have.

### PR DESCRIPTION
**Pull request by makepost**
Resolves #221. Please review and test.

### CODE REVIEW

**Comment by makepost** [comment]
@jonschlinkert What should I fix?

**Comment by cnnblike** [comment]
Maybe you could add this to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by makepost** [comment]
Hello @cnnblike,

Your comment seems gone. Please confirm that you need the definitions. 
If so, as soon as I have time I will move them to DefinitelyTyped.

Cheers,
Makepost

**Comment by cnnblike** [comment]
@makepost 
Your definition files look pretty solid, why not?

**Pull request closed without merging**
