### PR TITLE
Update argparse

### PR DESCRIPTION
**Pull request by rejas**
Mainly to fix the https://snyk.io/test/npm/modernizr security alert

### CODE REVIEW

**Comment by jskainos** [comment]
Bumping for attention

**Comment by pwright08** [comment]
+1

**Comment by jonschlinkert** [comment]
@rejas please update your commit to only include the dependency update.

**Comment by jonschlinkert** [comment]
actually this is a duplicate of https://github.com/jonschlinkert/remarkable/pull/312

**Pull request closed without merging**
