### PR TITLE
Outlaw data: URLs by default

### PR DESCRIPTION
**Pull request by spicyj**
See #227. It would still be better to switch to a whitelist but this is an improvement.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@spicyj thanks! I'll review and get this merged asap.

**Comment by adjenks** [comment]
Please document this change. I couldn't understand why data tags were working on the demo but not on my website. I used the old version and it worked so I had to look at the changes that were made to the source to figure out the problem and I finally figured out that I had to override the validateLink function.
I filed another issue about documentation previously: #303

**Comment by adjenks** [comment]
I understand that the data tags are a security issue but the md files are not edited by users on my page, only by devs, so it's a non-issue. I would appreciate if the documentation explained how and under what circumstances to override the function.

**Comment by kubukoz** [comment]
For anyone looking, you can override this if you're absolutely sure nobody can submit content to be rendered in a way prone to XSS:

```javascript
md.inline.validateLink = (_) => true;
```

I'm using this in docusaurus, so in my `siteConfig.js` I have:

```javascript
markdownPlugins: [
    (md) => md.inline.validateLink = (_) => true;
]
```

**Pull request merged**
