### PR TITLE
Support for specifying link target

### PR DESCRIPTION
**Pull request by pkfladset**
Adds supports for specifying link target and resolves issue #171

This also corrects some lint errors and completes renaming from samle -> example in demo files

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks! it looks good to me, but I might not be able to get to this soon so I added you as a collab,  feel free to merge. 

much appreciated

**Comment by jonschlinkert** [comment]
I can add you to npm too if you want. I'll need your username

**Comment by pkfladset** [comment]
Great! Its the same as my github user: pkfladset
_____________________________

**Comment by jonschlinkert** [comment]
done! you're all set!

**Comment by tommysanterre** [comment]
@pkfladset @jonschlinkert could you publish the changes on npm?

**Comment by pkfladset** [comment]
@tommysanterre published now. See that I missed to updated the README with the new option, but will fix it

**Comment by tommysanterre** [comment]
@pkfladset great, thanks creating the feature and publishing it

**Comment by jonschlinkert** [comment]
great, thank you!

**Comment by pkfladset** [comment]
Happy to contribute! @jonschlinkert master and dev diverted related to 1.6.1 and I continued to it with this release. How would you like the merge and release strategy to be in the future?

**Comment by jonschlinkert** [comment]
I think it makes sense to base the strategy on the team's preferences, I trust your judgement! thank you

**Pull request merged**
