### PR TITLE
Upgrade autolinker

### PR DESCRIPTION
**Pull request by TrySound**
Refs https://github.com/jonschlinkert/remarkable/pull/340 and https://github.com/gregjacobs/Autolinker.js/releases

- fixed test
- dropped twitter option
- dropped rollup commonjs plugin as autolinker is distributed as esm now

/cc @kibertoad

### CODE REVIEW

**Comment by TrySound** [comment]
Friendly ping @jonschlinkert @doowb @shockey

**Comment by kibertoad** [comment]
@TrySound Are you sure you fixed and didn't break the test? See https://github.com/gregjacobs/Autolinker.js/issues/278

**Comment by TrySound** [comment]
Damn, missed your comment in that PR

**Comment by TrySound** [comment]
I see in this test that such behaviour is expected.
https://github.com/gregjacobs/Autolinker.js/blob/master/tests/autolinker-url.spec.ts#L201

**Comment by kibertoad** [comment]
@TrySound Considering https://github.com/jonschlinkert/remarkable/issues/51, I'm not sure this was intentional behaviour.

**Comment by TrySound** [comment]
I extended version range so users could upgrade autolinker when the new version is out.

Of the behaviour will not fit to users they may copy paste lunkify plugin into own code base and use any lib and version wothout any loss. Linkify plugin is a separate entry point now.

**Pull request merged**
